@startuml Fahrzeugverwaltung
abstract class Fahrzeug {
  - marke: String
  - modell: String
  - baujahr: int
  - anzahlReifen: int
  + starten(): void
  + zeigeFahrzeugInformationen(): void
  + wechsleReifen(): void
}
class PKW extends Fahrzeug {
  - anzahlTueren: int
  + PKW(marke: String, modell: String, baujahr: int, anzahlTueren: int)
  + starten(): void
  + zeigeFahrzeugInformationen(): void
  + wechsleReifen(): void
}

class Motorrad extends Fahrzeug {
  - helmfachVorhanden: boolean
  - helmfachGeöffnet: boolean
  + Motorrad(marke: String, modell: String, baujahr: int, helmfachVorhanden: boolean)
  + starten(): void
  + zeigeFahrzeugInformationen(): void
  + wechsleReifen(): void
  + öffneHelmfach(): void
  + schließeHelmfach(): void
}

class LKW extends Fahrzeug {
  - ladekapazitaet: float
  + Motorrad(marke: String, modell: String, baujahr: int, ladekapazitaet: float)
  + starten(): void
  + zeigeFahrzeugInformationen(): void
  + wechsleReifen(): void
  + ladeLadung(gewicht: float): void
}

class Fahrzeughausverwaltung {
  - fahrzeuge: List<Fahrzeug>
  + Fahrzeughausverwaltung()
  + hinzufuegen(f: Fahrzeug): void
  + zeigeFahrzeugInfo(f: Fahrzeug): void
  + fuehreReifenwechselDurch(f: Fahrzeug): void
}